spring:
  datasource:
    url: jdbc:sqlserver://javatechiee.database.windows.net:1433;database=javatechiedb;user=javatechie@javatechiee;password=Nadu23!23;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: javatechie
    password: Nadu23!23


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


